const SEMINARS = [
  // === Upcoming ===
  {
    speaker: "Songlin Yang",
    speaker_url: "https://sustcsonglin.github.io/",
    affiliation: "MIT CSAIL and Thinking Machines Lab",
    title: "TBD",
    date: "2025-12-15",
    status: "upcoming"
  },
  {
    speaker: "Zita Marinho",
    speaker_url: "https://isr.tecnico.ulisboa.pt/author/zitaalexandramagalhaesmarinho/",
    affiliation: "Google Deepmind and IST",
    title: "TBD",
    date: "2026-01-05",
    status: "upcoming"
  },

  // === Past ===
  {
    speaker: "João Maria Janeiro",
    speaker_url: "",
    affiliation: "FAIR at Meta and Sorbonne Université",
    title: "Mixture of Languages: Improved Multilingual Encoders Through Language Grouping",
    date: "2025-11-24",
    status: "past",
    slides_url: "https://drive.google.com/file/d/1jxjw0Rh-HRD94Gp9fVojxxqLmC24ubtU/view?usp=drive_web",
    paper_url: "https://aclanthology.org/2025.emnlp-main.1509/",
    video_url: "https://www.youtube.com/watch?v=cd6Lhhh6lPI",
  },
  {
    speaker: "Vilém Zouhar",
    speaker_url: "",
    affiliation: "ETH Zürich",
    title: "Quality and Quantity of Machine Translation References for Automated Metrics",
    date: "2024-01-22",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Haoran Xu",
    speaker_url: "",
    affiliation: "Johns Hopkins University",
    title: "Pushing the Boundaries of LLM Performance in Machine Translation",
    date: "2024-01-29",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Tom Kocmi and Vilém Zouhar",
    speaker_url: "",
    affiliation: "Microsoft and ETH Zürich",
    title: "Navigating the Metrics Maze: Reconciling Score Magnitudes and Accuracies",
    date: "2024-02-05",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Giorgos Vernikos",
    speaker_url: "",
    affiliation: "EPFL",
    title: "Don't Rank, Combine! Combining Machine Translation Hypotheses Using Quality Estimation",
    date: "2024-02-12",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Haikang Deng",
    speaker_url: "",
    affiliation: "UT Austin",
    title:
      "Reward-Augmented Decoding: Efficient Controlled Text Generation With a Unidirectional Reward Model",
    date: "2023-12-18",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Prasann Singhal",
    speaker_url: "",
    affiliation: "UT Austin",
    title:
      "A Long Way to Go: Investigating Length Correlations in RLHF",
    date: "2023-11-13",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Mara Finkelstein and Markus Freitag",
    speaker_url: "",
    affiliation: "Google Research",
    title:
      "MBR and QE Finetuning: Training-time Distillation of the Best and Most Expensive Decoding Methods",
    date: "2023-11-06",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "João Sacramento",
    speaker_url: "",
    affiliation: "ETH Zurich",
    title: "Uncovering mesa-optimization algorithms in Transformers",
    date: "2023-10-30",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Elena Voita",
    speaker_url: "",
    affiliation: "Meta AI",
    title: "Neurons in Large Language Models",
    date: "2023-10-23",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Tri Dao",
    speaker_url: "",
    affiliation: "Stanford and Together.AI",
    title:
      "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
    date: "2023-10-09",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
  {
    speaker: "Jason Wei",
    speaker_url: "",
    affiliation: "OpenAI",
    title: "Scaling, emergence, and reasoning in large language models",
    date: "2023-09-18",
    status: "past",
    slides_url: "",
    paper_url: "",
    video_url: "",
  },
];
