const SEMINARS = [
  // === Upcoming ===
  {
    speaker: "Marcely Zanon Boito",
    speaker_url: "https://mzboito.github.io",
    affiliation: "Naver Labs Europe",
    title: "TBD",
    date: "2026-06-08",
    status: "",
    paper_url: "",
    slides_url: "",
    video_url: "",
  },
  {
    speaker: "Luís Marques",
    speaker_url: "https://luis-marques.github.io",
    affiliation: "University of Michigan",
    title: "TBD (in person)",
    date: "2026-05-25",
    status: "",
    paper_url: "",
    slides_url: "",
    video_url: "",
  },
  {
    speaker: "Kangrui Wang",
    speaker_url: "",
    affiliation: "Northwestern University",
    title: "VAGEN:Reinforcing World Model Reasoning for Multi-Turn VLM Agents",
    date: "TBD",
    status: "",
    paper_url: "https://arxiv.org/html/2510.16907v1",
    slides_url: "",
    video_url: "",
  },
  // === Past ===
  {
    speaker: "Peter Hase",
    speaker_url: "https://peterbhase.github.io",
    affiliation: "Schmidt Sciences and Stanford University",
    title: "LLM Interpretability: Faithful Reasoning and Controllable Knowledge",
    date: "2026-04-13",
    status: "past",
    paper_url: "",
    slides_url: "",
    video_url: "https://drive.google.com/file/d/1pPAo8AHI2eXGxXC1z96lSwUJNEsSdGkQ/view?usp=sharing",
  },
  {
    speaker: "Swabha Swayamdipta",
    speaker_url: "https://swabhs.com",
    affiliation: "USC Viterbi CS",
    title: "Small Samples, Big Reveal: What can we learn from limited observations of language model behavior?",
    date: "2026-03-30",
    status: "past",
    paper_url: "",
    slides_url: "",
    video_url: "https://drive.google.com/file/d/1woblxjwuHIulIWdfyhWHikQYKPqJhUJy/view?usp=sharing",
  },
  {
    speaker: "Jonas Hübotter",
    speaker_url: "https://jonhue.github.io",
    affiliation: "ETH Zürich",
    title: "Rethinking Post-Training with Self-Distillation",
    date: "2026-03-16",
    status: "past",
    paper_url: "",
    slides_url: "",
    video_url: "https://drive.google.com/file/d/1QBFbRhWJfbH47GQhwBdhsqG-KdscHdTU/view?usp=sharing",
  },
  {
    speaker: "Federico Bianchi",
    speaker_url: "https://federicobianchi.io",
    affiliation: "Together AI",
    title: "Learning to Discover at Test Time",
    date: "2026-02-16",
    status: "past",
    paper_url: "",
    slides_url: "",
    video_url: "",
  },
  {
    speaker: "Aitor Gonzalez-Agirre & Júlia Falcão",
    speaker_url: "https://www.bsc.es/gonzalez-aguirre-aitor",
    affiliation: "BSC Language Technologies Laboratory",
    title: "Unlocking the Potential of Multilingual Language Models",
    date: "2026-03-02",
    status: "past",
    paper_url: "",
    slides_url: "",
    video_url: "https://drive.google.com/file/d/1leDEHII6evMiX8Ch1n7S_93m33n4AIu7/view?usp=sharing",
  },
  {
    speaker: "Gonçalo Faria",
    speaker_url: "https://www.goncalofaria.com",
    affiliation: "University of Washington",
    title: "Sample, Don't Search: Rethinking Test-Time Alignment for Language Models",
    date: "2026-02-02",
    status: "past",
    paper_url: "https://arxiv.org/pdf/2504.03790",
    slides_url: "",
    video_url: "https://drive.google.com/file/d/1VH2u6q4n6hRPkLoxXqqJjmje1-GGAh1J/view?usp=sharing",
  },
  {
    speaker: "Ammar Khairi & Julia Kreutzer",
    speaker_url: "https://cohere.com/research",
    affiliation: "Cohere Labs",
    title: "From Data to Inference: Optimizing Multilingual Performance",
    date: "2026-01-19",
    status: "past",
    paper_url: "https://arxiv.org/pdf/2506.20544",
    slides_url: "https://docs.google.com/presentation/d/1iNsOayx7dRicC9rUbw7V8x15H8WbSv8g/edit?usp=sharing&ouid=100143296807313756807&rtpof=true&sd=true",
    video_url: "https://drive.google.com/file/d/1G1NwLAeY8RjWr6tNBdR_cUvSlmhkiV8I/view?usp=sharing",
  },
  {
    speaker: "Zita Marinho",
    speaker_url: "https://isr.tecnico.ulisboa.pt/author/zitaalexandramagalhaesmarinho/",
    affiliation: "IST/University of Lisbon",
    title: "RL in the era of LLMs",
    date: "2026-01-05",
    status: "past",
    paper_url: "",
    slides_url: "https://drive.google.com/file/d/1g7tlQ39B1jeN11Qtbxc12udqgu6gSicQ/view?usp=sharing",
    video_url: "",
  },
  {
    speaker: "João Maria Janeiro",
    speaker_url: "",
    affiliation: "FAIR at Meta and Sorbonne Université",
    title: "Mixture of Languages: Improved Multilingual Encoders Through Language Grouping",
    date: "2025-11-24",
    status: "past",
    paper_url: "https://aclanthology.org/2025.emnlp-main.1509/",
    slides_url: "https://drive.google.com/file/d/1jxjw0Rh-HRD94Gp9fVojxxqLmC24ubtU/view?usp=drive_web",
    video_url: "https://www.youtube.com/watch?v=cd6Lhhh6lPI",
  },
];
